Forgot/Recover Password
SkillBrainFrontend/Semicolon-Task-Manager-Andromeda pull request #22
Opened 2022-09-20 19:58 UTC by pirvanrobert

gata BAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

2022-09-20 20:02 UTC, Adrian-Edu commented
aaaa

2022-09-20 20:11 UTC, shapovalov-sasha requested changes

2022-09-20 20:11 UTC, shapovalov-sasha commented on src/App.jsx
> +				<Route element={<RecoverPassword />} path="/recoverPass" />
```suggestion
				<Route element={<RecoverPassword />} path="/recover-password" />
```

2022-09-20 20:11 UTC, shapovalov-sasha commented on src/pages/reset-password/ResetPassword.jsx
> +import { Box } from "@mui/material";
```suggestion
import { Box, Typography } from "@mui/material";
```

2022-09-20 20:11 UTC, shapovalov-sasha commented on src/pages/reset-password/ResetPassword.jsx
> +import Typography from "@mui/material/Typography";
```suggestion

```

2022-09-20 20:14 UTC, Adrian-Edu commented
e ok

2022-09-21 16:39 UTC, shapovalov-sasha approved these changes

2022-09-21 16:43 UTC, Eladie approved these changes

2022-09-21 16:43 UTC, merged